- name: gathering facts
  hosts: web
  become: yes
  tasks:
    - name: print the facts
      ansible.builtin.debug:
        msg: "facts are {{ansible_facts}}"

    - name: install nginx if redhat
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: install nginx if debian #for ubuntu
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"
