- name: command vs shell
  hosts: local
  connection: local
  tasks:
    - name: execute the command
      ansible.builtin.shell: ls -ltr > /tmp/output.txt
      #shell goes into the server ......so command is secure than shell

    - name: check the process
      ansible.builtin.command: ps -ef | grep ssh
      register: output
