- name: devops course info
  hosts: local
  vars:
    course: "devops with aws" #string
    duration: 120 #number
    topics: #list
      - list
      - shell
      - ansible
    live: true #boolean
    tools: #map/dictionary
      ci: jenkins
      cm: ansible
      cloud: aws

  tasks:
    - name: print the course info
      ansible.builtin.debug:
        msg: "hi course is {{course}} and the duration is {{duration}} and topics are {{topics}} and live is {{live}} and tools are {{tools}}"
