- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
    - name: print the default varaiable
      ansible.builtin.debug:
        msg: "hello {{COURSE | default(5)}}" #or 'ansible' at 5 prints hello ansible

    - name: convert to upper case
      vars:
        greeting: "hello ramesh"
      ansible.builtin.debug:
        msg: "{{greeting | upper }}"

    - name: convert to lower case
      vars:
        greeting: "hello ramesh"
      ansible.builtin.debug:
        msg: "{{greeting | lower }}"

    - name: get the unique values
      vars:
        numbers: [1, 2, 3, 45, 56, 3, 2, 1, 567]
      ansible.builtin.debug:
        msg: "{{numbers | unique}}"

    - name: get the minimum values
      vars:
        numbers: [1, 2, 3, 45, 56, 3, 2, 1, 567]
      ansible.builtin.debug:
        msg: "{{numbers | min}}"

    - name: get the maximum values
      vars:
        numbers: [1, 2, 3, 45, 56, 3, 2, 1, 567]
      ansible.builtin.debug:
        msg: "{{numbers | max}}"

    - name: convert maps to list
      vars:
        course:
          name: "devops with aws"
          duration: 120
      ansible.builtin.debug:
        msg: "{{course | dict2items}}"

    - name: convert lists to map
      vars:
        course:
          - { "key": "name", "value": "devops with aws" }
          - { "key": "duration", "value": 120 }

      ansible.builtin.debug:
        msg: "{{course | items2dict}}"
